<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Catálogo etnobotánico de especies útiles — "Tabla 2" del cuestionario
 * de etnobotánica (Sumapaz, 2026). Carga 56 fichas de uso
 * repartidas entre Medicina, Alimentación y Cultura, cada una con su
 * parte utilizada, uso reportado, forma de preparación y origen.
 *
 * Como los subtemas ya sembrados (Diabetes / Tensión Alta / Digestión en
 * Medicina; Rituales y ceremonias / Tintes naturales / Construcción
 * ancestral en Cultura) no cubrían todos los usos reportados, este
 * seeder crea dos subtemas nuevos:
 *  - "Otros usos medicinales" (Medicina): usos medicinales que no encajan
 *    en Diabetes, Digestión ni Primeros auxilios y heridas.
 *  - "Cuidado ambiental" (Cultura): uso ambiental/ecológico (el Aliso).
 *
 * Cuando una planta ya existía en Medicina/Alimentación/Cultura por el
 * seeder de videos del Sumapaz (Fique en concreto), no se repite aquí
 * para no sobrescribir esas fichas con contenido menos detallado.
 */
class Tabla2PlantasUsoSeeder extends Seeder
{
    public function run(): void
    {
        $medicinaId = DB::table('categorias')->where('nombre', 'Medicina')->value('id');
        $alimentacionId = DB::table('categorias')->where('nombre', 'Alimentación')->value('id');
        $culturaId = DB::table('categorias')->where('nombre', 'Cultura')->value('id');

        if (!$medicinaId || !$alimentacionId || !$culturaId) {
            return;
        }

        // Subtemas nuevos que no existían.
        DB::table('subtemas')->updateOrInsert(
            ['categoria_id' => $medicinaId, 'nombre' => 'Otros usos medicinales'],
            ['creado_en' => now()]
        );
        DB::table('subtemas')->updateOrInsert(
            ['categoria_id' => $culturaId, 'nombre' => 'Cuidado ambiental'],
            ['creado_en' => now()]
        );

        $categoriaIds = [
            'Medicina'     => $medicinaId,
            'Alimentación' => $alimentacionId,
            'Cultura'      => $culturaId,
        ];

        $subtemaCache = [];
        $subtemaId = function (string $categoria, string $subtema) use ($categoriaIds, &$subtemaCache) {
            $key = $categoria . '|' . $subtema;
            if (!isset($subtemaCache[$key])) {
                $subtemaCache[$key] = DB::table('subtemas')
                    ->where('categoria_id', $categoriaIds[$categoria])
                    ->where('nombre', $subtema)
                    ->value('id');
            }
            return $subtemaCache[$key];
        };

        $plantas = [
            [
                'nombre'         => 'Ajenjo',
                'cientifico'     => 'Artemisia absinthium',
                'categoria'      => 'Medicina',
                'subtema'        => 'Digestión',
                'uso'            => 'Alivio de indigestión',
                'instrucciones'  => 'Preparar en infusión con las hojas.',
                'contexto'       => 'Uso reportado en el cuestionario de etnobotánica para aliviar la indigestión. Parte utilizada: hojas. Origen: silvestre.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/eb/Artemisia_absinthium_P1210748.jpg/960px-Artemisia_absinthium_P1210748.jpg',
                'tags'           => 'medicina,digestion,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Anís',
                'cientifico'     => 'Pimpinella anisum',
                'categoria'      => 'Medicina',
                'subtema'        => 'Digestión',
                'uso'            => 'Alivio de problemas digestivos',
                'instrucciones'  => 'Preparar en infusión con flores, hojas y tallo.',
                'contexto'       => 'Reportada tanto como alimento como remedio para problemas digestivos. Origen: cultivada y silvestre.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c0/Foeniculum_July_2011-1a.jpg/960px-Foeniculum_July_2011-1a.jpg',
                'tags'           => 'medicina,digestion,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Aulaga / Arantú - Malamadre',
                'cientifico'     => 'Kalanchoe daigremontiana',
                'categoria'      => 'Medicina',
                'subtema'        => 'Digestión',
                'uso'            => 'Uso digestivo',
                'instrucciones'  => 'Masticar una hoja directamente.',
                'contexto'       => 'Se reporta también su uso popular para "tratar tumores cancerígenos"; esta es una creencia tradicional recogida en la encuesta, sin respaldo médico-científico confirmado, por lo que no debe interpretarse como tratamiento oncológico.',
                'img_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Zyworodka_-_Kalanchoe_daigremontiana.JPG/960px-Zyworodka_-_Kalanchoe_daigremontiana.JPG',
                'tags'           => 'medicina,digestion,sumapaz',
                'verificada'     => false,
            ],
            [
                'nombre'         => 'La Ruda',
                'cientifico'     => 'Ruta graveolens',
                'categoria'      => 'Medicina',
                'subtema'        => 'Digestión',
                'uso'            => 'Alivio de dolor de estómago y cólicos',
                'instrucciones'  => 'Preparar en infusión con las hojas.',
                'contexto'       => 'Reportada para calmar el dolor de estómago y los cólicos. Origen: cultivada.',
                'img_url'        => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQH9mR2HHEljjDwBoInIdxlPr3uVvJvJmu_WOIhf4CYsCJIhzUatPWvOxHt&s=10',
                'tags'           => 'medicina,digestion,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Mirto',
                'cientifico'     => 'Myrtus communis',
                'categoria'      => 'Medicina',
                'subtema'        => 'Digestión',
                'uso'            => 'Alivio de trastornos digestivos',
                'instrucciones'  => 'Preparar en infusión con las hojas.',
                'contexto'       => 'Origen: cultivada.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/%28MHNT%29_Myrtus_communis_subsp._tarentina.jpg/960px-%28MHNT%29_Myrtus_communis_subsp._tarentina.jpg',
                'tags'           => 'medicina,digestion,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Orégano',
                'cientifico'     => 'Origanum vulgare',
                'categoria'      => 'Medicina',
                'subtema'        => 'Digestión',
                'uso'            => 'Alivio de cólicos',
                'instrucciones'  => 'Preparar en infusión con las hojas.',
                'contexto'       => 'Origen: cultivada.',
                'img_url'        => 'https://tienda.ecoyuma.com.co/811-large_default/oregano.jpg',
                'tags'           => 'medicina,digestion,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Paico',
                'cientifico'     => 'Dysphania ambrosioides',
                'categoria'      => 'Medicina',
                'subtema'        => 'Digestión',
                'uso'            => 'Purgante y digestivo',
                'instrucciones'  => 'Preparar en infusión, o bien machacar de 5 a 7 hojas, colar el zumo y tomar con agua.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUix7jKJXayz-JUo-k06dkwLtndE2nsDy_0fxHqmvMFfCTcUqNlDoyEQw_&s=10',
                'tags'           => 'medicina,digestion,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Berbena',
                'cientifico'     => 'Verbena officinalis',
                'categoria'      => 'Medicina',
                'subtema'        => 'Digestión',
                'uso'            => 'Purgante',
                'instrucciones'  => 'Preparar en infusión con hojas y tallos.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://nativegardenhub.org/wp-content/uploads/2025/03/1Nh01QJHSxGur5xMlVareYd0_VGXHDE4e-scaled.webp',
                'tags'           => 'medicina,digestion,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Insulina',
                'cientifico'     => 'Cissus verticillata',
                'categoria'      => 'Medicina',
                'subtema'        => 'Diabetes',
                'uso'            => 'Apoyo en el control de azúcar',
                'instrucciones'  => 'Preparar en infusión con tallos y hojas.',
                'contexto'       => 'Origen: cultivada.',
                'img_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Cissus_verticillata_2.jpg/960px-Cissus_verticillata_2.jpg',
                'tags'           => 'medicina,diabetes,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Arnica',
                'cientifico'     => 'Arnica montana',
                'categoria'      => 'Medicina',
                'subtema'        => 'Primeros auxilios y heridas',
                'uso'            => 'Ayuda en la recuperación de huesos',
                'instrucciones'  => 'Preparar en infusión con hojas y tallos.',
                'contexto'       => 'Nota: el uso interno del árnica en dosis altas puede ser tóxico; tradicionalmente también se emplea de forma tópica (compresas). Origen: cultivada.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dd/Arnica_montana_L._3343971462.jpg/960px-Arnica_montana_L._3343971462.jpg',
                'tags'           => 'medicina,primeros-auxilios,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Artemisa',
                'cientifico'     => 'Artemisia vulgaris',
                'categoria'      => 'Medicina',
                'subtema'        => 'Primeros auxilios y heridas',
                'uso'            => 'Control de hemorragias',
                'instrucciones'  => 'Preparar en infusión con las hojas.',
                'contexto'       => 'Origen: cultivada.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/ArtemisiaVulgaris.jpg/960px-ArtemisiaVulgaris.jpg',
                'tags'           => 'medicina,primeros-auxilios,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Nopal',
                'cientifico'     => 'Opuntia ficus-indica',
                'categoria'      => 'Medicina',
                'subtema'        => 'Primeros auxilios y heridas',
                'uso'            => 'Alivio de dolor de espolón y dolores musculares',
                'instrucciones'  => 'Licuar la pulpa y adicionar los frutos.',
                'contexto'       => 'Origen: cultivada.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ef/Opuntia_sp._Opuncja_2023-02-22_03.jpg/960px-Opuntia_sp._Opuncja_2023-02-22_03.jpg',
                'tags'           => 'medicina,primeros-auxilios,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Sábila',
                'cientifico'     => 'Aloe vera',
                'categoria'      => 'Medicina',
                'subtema'        => 'Primeros auxilios y heridas',
                'uso'            => 'Alivio de quemaduras',
                'instrucciones'  => 'Aplicar la penca o el tallo directamente sobre la piel.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqRklqzB7gPkWLX1cVWdTwohhyxyt7Bqfo-ftVoigPzA&s',
                'tags'           => 'medicina,primeros-auxilios,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Suelda con Suelda',
                'cientifico'     => 'Chiococca alba',
                'categoria'      => 'Medicina',
                'subtema'        => 'Primeros auxilios y heridas',
                'uso'            => 'Antiinflamatorio para dolor articular',
                'instrucciones'  => 'Preparar en infusión con hojas y tallos.',
                'contexto'       => 'Origen: silvestre.',
                'img_url'        => 'https://www.planteaenverde.es/wp-content/uploads/consuelda.jpg',
                'tags'           => 'medicina,primeros-auxilios,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Bejuco Lechero',
                'cientifico'     => 'No determinado con certeza',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Estimula la lactancia',
                'instrucciones'  => 'Preparar en infusión con las hojas.',
                'contexto'       => 'Origen: silvestre.',
                'img_url'        => 'https://www.picturethisai.com/wiki-image/1080/154011836444835856.jpeg',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => false,
            ],
            [
                'nombre'         => 'Berbena',
                'cientifico'     => 'Verbena officinalis',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Control de la fiebre',
                'instrucciones'  => 'Preparar en infusión con hojas y tallo.',
                'contexto'       => 'Origen: cultivada.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4f/Verbena_officinalis_kz09.jpg/960px-Verbena_officinalis_kz09.jpg',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Caléndula',
                'cientifico'     => 'Calendula officinalis',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Uso medicinal y cosmético',
                'instrucciones'  => 'Preparar emplastos o pasta para untar sobre la piel.',
                'contexto'       => 'También se reporta su uso cosmético. Origen: cultivada y silvestre.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9e/Ringelblume_%28Calendula_officinalis%29_Bl%C3%BCte_focus_stack-20220623-RM-174041.jpg/960px-Ringelblume_%28Calendula_officinalis%29_Bl%C3%BCte_focus_stack-20220623-RM-174041.jpg',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Cannabis',
                'cientifico'     => 'Cannabis sativa',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Uso medicinal (tipo cáñamo)',
                'instrucciones'  => 'Preparar emplastos o pasta para untar sobre la piel.',
                'contexto'       => 'Variedad reportada tipo cáñamo. Origen: cultivada y silvestre.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dd/Cannabis_sativa_plant_%284%29.JPG/960px-Cannabis_sativa_plant_%284%29.JPG',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Cilantrón o Cimarrón',
                'cientifico'     => 'Eryngium foetidum',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Uso tradicional para afecciones hepáticas',
                'instrucciones'  => 'Preparar en caldos.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQW0QEFsVSfkC0v4o-rGZHRDAmxHLdEp_I-l6EVeB9LhGf8lBpnSp0hmBI4&s=10',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Coca',
                'cientifico'     => 'Erythroxylum coca',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Uso medicinal tradicional',
                'instrucciones'  => 'Preparar emplastos o pasta para untar sobre la piel.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c1/Planta_de_la_Coca_%28Erythroxylum_coca%29.jpg/960px-Planta_de_la_Coca_%28Erythroxylum_coca%29.jpg',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Cola de Caballo',
                'cientifico'     => 'Equisetum bogotense',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Apoyo para los riñones',
                'instrucciones'  => 'Preparar en infusión con toda la planta, incluidas las raíces.',
                'contexto'       => 'Origen: cultivada.',
                'img_url'        => 'https://media.glamour.mx/photos/64ff554b12a8facf90ab30e7/3:2/w_2560%2Cc_limit/cola-de-caballo-beneficios-para-el-pelo.png',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Enebro',
                'cientifico'     => 'Juniperus communis',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Uso medicinal general',
                'instrucciones'  => 'Preparar en infusión con las hojas.',
                'contexto'       => 'Origen: cultivada.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1e/Juniperus_communis_fruits_-_Keila.jpg/960px-Juniperus_communis_fruits_-_Keila.jpg',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => false,
            ],
            [
                'nombre'         => 'Eneldo',
                'cientifico'     => 'Anethum graveolens',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Control de colesterol',
                'instrucciones'  => 'Preparar en infusión con las hojas.',
                'contexto'       => 'Origen: cultivada.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/66/Dill_Bluete_7080848-PSD-2.jpg/960px-Dill_Bluete_7080848-PSD-2.jpg',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Jengibre',
                'cientifico'     => 'Zingiber officinale',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Alivio del resfriado',
                'instrucciones'  => 'Usar en trocitos, rallado o en infusión con la raíz.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/64/Ingwer_%28Zingiber_officinale%29_Freiland_Anbau_Pflanze-3-Josef_Schlaghecken.jpg/960px-Ingwer_%28Zingiber_officinale%29_Freiland_Anbau_Pflanze-3-Josef_Schlaghecken.jpg',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Mejorana',
                'cientifico'     => 'Origanum majorana',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Combate el insomnio y las migrañas; tranquilizante',
                'instrucciones'  => 'Preparar en infusión con las hojas.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d6/Origanum_majorana.jpg/1280px-Origanum_majorana.jpg',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Melisa',
                'cientifico'     => 'Melissa officinalis',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Tranquilizante y regulador del ciclo menstrual',
                'instrucciones'  => 'Preparar en infusión con las hojas.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/02014_Melissa_officinalis.JPG/250px-02014_Melissa_officinalis.JPG',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Pepa de Neuro',
                'cientifico'     => 'Terminalia catappa',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Fortalece el sistema inmunológico',
                'instrucciones'  => 'Triturar la mitad de la almendra y comer junto con otros alimentos.',
                'contexto'       => 'Origen: cultivada.',
                'img_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Terminalia_Catappa_D8348.jpg/960px-Terminalia_Catappa_D8348.jpg',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => false,
            ],
            [
                'nombre'         => 'Pulmonaria',
                'cientifico'     => 'Pulmonaria officinalis',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Alivio de afecciones pulmonares (asma, tos, bronquitis)',
                'instrucciones'  => 'Hervir un puñado de la planta (raíz, tallo y hojas) en un litro de agua.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://upload.wikimedia.org/wikipedia/commons/7/71/Pulmonaria_officinalis_800.jpg',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Ruda Castilla',
                'cientifico'     => 'Ruta graveolens',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Alivio del dolor de cabeza',
                'instrucciones'  => 'Preparar en infusión con las hojas.',
                'contexto'       => 'Origen: cultivada.',
                'img_url'        => 'https://sembramos.com.co/wp-content/uploads/2021/04/ARMONIA-30.png',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Ruda de Tierra',
                'cientifico'     => 'No determinado con certeza',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Alivio de cólicos posparto',
                'instrucciones'  => 'Preparar en infusión con las hojas.',
                'contexto'       => 'Identificación taxonómica no confirmada con certeza. Origen: cultivada.',
                'img_url'        => 'https://www.elmundoforestal.com/wp-content/uploads/2020/10/ruda-1.jpg',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => false,
            ],
            [
                'nombre'         => 'Salvia',
                'cientifico'     => 'Salvia officinalis',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Alivio de molestias de la menopausia y regulación menstrual',
                'instrucciones'  => 'Preparar en infusión con las hojas.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://upload.wikimedia.org/wikipedia/commons/5/5d/Salvia_officinalis_Habitus_DehesaBoyalPuertollano.jpg',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Sauce',
                'cientifico'     => 'Salix humboldtiana',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Alivio de la gripa',
                'instrucciones'  => 'Preparar en infusión con hojas y tallo.',
                'contexto'       => 'Origen: silvestre.',
                'img_url'        => 'https://upload.wikimedia.org/wikipedia/commons/1/15/Sauce_Patag%C3%B3nico.jpg',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Tres Cogollos',
                'cientifico'     => 'No determinado con certeza',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Uso tradicional antiofídico',
                'instrucciones'  => 'Comer directamente 3 cogollos.',
                'contexto'       => 'Uso reportado en la medicina tradicional como antiofídico, vasodilatador y anticoagulante. Ante una mordedura de serpiente real se debe buscar atención médica de emergencia de inmediato: no existe evidencia científica de que esta planta sustituya el suero antiofídico. Especie crece en selvas tropicales del Pacífico Sur; identificación no confirmada con certeza.',
                'img_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Zwellende_bloemknoppen_van_Chaenomeles_x_superba_%27nicolina%27_%28chinese_kwee%29._Locatie._Tuinreservaat_Jonkervallei_02.jpg/960px-Zwellende_bloemknoppen_van_Chaenomeles_x_superba_%27nicolina%27_%28chinese_kwee%29._Locatie._Tuinreservaat_Jonkervallei_02.jpg',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => false,
            ],
            [
                'nombre'         => 'Yerbabuena',
                'cientifico'     => 'Mentha spicata',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Alivio de afecciones pulmonares y aftas bucales',
                'instrucciones'  => 'Preparar en infusión con toda la planta.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://pymstatic.com/28531/conversions/hierbabuena-wide.jpg',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Gusanero',
                'cientifico'     => 'No determinado con certeza',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Uso medicinal (resina)',
                'instrucciones'  => 'Preparar en infusión con la corteza.',
                'contexto'       => 'Identificación taxonómica no confirmada con certeza. Origen: cultivada y silvestre.',
                'img_url'        => 'https://catalogofloravalleaburra.eia.edu.co/storage/images/d7e7bd0058c3c3103f47be0993ad3f876f2c60c4.jpg',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => false,
            ],
            [
                'nombre'         => 'Curuba India',
                'cientifico'     => 'Passiflora tripartita var. mollissima',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Uso medicinal general',
                'instrucciones'  => 'Preparar en sorbete con el fruto.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_I8Uyd0fdFNDU2tbNp_2HeQM3snWnFoo2mdbIeIlj7Q&s=10',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Chivaco',
                'cientifico'     => 'No determinado con certeza',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Uso medicinal general',
                'instrucciones'  => 'Preparar en infusión con corteza, hojas y flores.',
                'contexto'       => 'Identificación taxonómica no confirmada con certeza. Origen: cultivada y silvestre.',
                'img_url'        => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVGPyiRAVW78Gzfv8tWCCfOYlBVo1c5H7RK4U3QzaXPNx881tWv7UjluMw&s=10',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => false,
            ],
            [
                'nombre'         => 'Reventadera',
                'cientifico'     => 'No determinado con certeza',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Uso medicinal general',
                'instrucciones'  => 'Masticar las espinas tiernas.',
                'contexto'       => 'Identificación taxonómica no confirmada con certeza. Origen: cultivada y silvestre.',
                'img_url'        => 'https://live.staticflickr.com/5538/9468713178_2c903df6ec_b.jpg',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => false,
            ],
            [
                'nombre'         => 'Pico',
                'cientifico'     => 'No determinado con certeza',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Uso medicinal general',
                'instrucciones'  => 'Preparar en infusión con las hojas.',
                'contexto'       => 'Identificación taxonómica no confirmada con certeza. Origen: cultivada y silvestre.',
                'img_url'        => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRP1_3Dj7fe3ekOw2CSUHd2pOVif_tzRmHlAIfQBX6mGS0zcDKm4Zawltk9&s=10',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => false,
            ],
            [
                'nombre'         => 'Pegamosco',
                'cientifico'     => 'Bejaria resinosa',
                'categoria'      => 'Medicina',
                'subtema'        => 'Otros usos medicinales',
                'uso'            => 'Uso medicinal general',
                'instrucciones'  => 'Preparar en infusión con las hojas.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Bejaria_resinosa%2C_Ericaceae_%2815357947388%29.jpg',
                'tags'           => 'medicina,otros,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Anís',
                'cientifico'     => 'Pimpinella anisum',
                'categoria'      => 'Alimentación',
                'subtema'        => 'Personas',
                'uso'            => 'Uso alimenticio',
                'instrucciones'  => 'Se usan flores, hojas y tallo como condimento o en infusión.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c0/Foeniculum_July_2011-1a.jpg/960px-Foeniculum_July_2011-1a.jpg',
                'tags'           => 'alimentacion,personas,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Cilantrón o Cimarrón',
                'cientifico'     => 'Eryngium foetidum',
                'categoria'      => 'Alimentación',
                'subtema'        => 'Personas',
                'uso'            => 'Condimento culinario',
                'instrucciones'  => 'Se usa en caldos.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQW0QEFsVSfkC0v4o-rGZHRDAmxHLdEp_I-l6EVeB9LhGf8lBpnSp0hmBI4&s=10',
                'tags'           => 'alimentacion,personas,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Orégano',
                'cientifico'     => 'Origanum vulgare',
                'categoria'      => 'Alimentación',
                'subtema'        => 'Personas',
                'uso'            => 'Condimento con propiedad antibiótica reportada',
                'instrucciones'  => 'Se usan las hojas como condimento, en infusión o directamente.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://tienda.ecoyuma.com.co/811-large_default/oregano.jpg',
                'tags'           => 'alimentacion,personas,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Jengibre',
                'cientifico'     => 'Zingiber officinale',
                'categoria'      => 'Alimentación',
                'subtema'        => 'Personas',
                'uso'            => 'Condimento culinario',
                'instrucciones'  => 'Usar en trocitos, rallado o en infusión con la raíz.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/64/Ingwer_%28Zingiber_officinale%29_Freiland_Anbau_Pflanze-3-Josef_Schlaghecken.jpg/960px-Ingwer_%28Zingiber_officinale%29_Freiland_Anbau_Pflanze-3-Josef_Schlaghecken.jpg',
                'tags'           => 'alimentacion,personas,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Romero',
                'cientifico'     => 'Salvia rosmarinus (Rosmarinus officinalis)',
                'categoria'      => 'Alimentación',
                'subtema'        => 'Personas',
                'uso'            => 'Condimento culinario',
                'instrucciones'  => 'Dejar secar las hojas en escamas antes de usarlas como condimento.',
                'contexto'       => 'También se reporta su uso cosmético, para disimular canas. Origen: cultivada y silvestre.',
                'img_url'        => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbx057cQsPcgLHURlt02igZXRCM5mZL5rHrZbAHyDdBKEfwXVpXb185gmW&s=10',
                'tags'           => 'alimentacion,personas,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Mora de Castilla',
                'cientifico'     => 'Rubus glaucus',
                'categoria'      => 'Alimentación',
                'subtema'        => 'Personas',
                'uso'            => 'Fruto alimenticio',
                'instrucciones'  => 'Se consume su fruto (en el reporte de la encuesta se anota el tallo como parte utilizada).',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0e/Rubus_glaucus_frutos_rojos.JPG/250px-Rubus_glaucus_frutos_rojos.JPG',
                'tags'           => 'alimentacion,personas,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Ramio',
                'cientifico'     => 'Boehmeria nivea',
                'categoria'      => 'Alimentación',
                'subtema'        => 'Animales',
                'uso'            => 'Alimentación animal (forraje proteico)',
                'instrucciones'  => 'Se usan las hojas directamente como forraje.',
                'contexto'       => 'Reportada como fuente de proteína para alimentación animal. Origen: cultivada y silvestre.',
                'img_url'        => 'https://a.storyblok.com/f/160385/b60f5dfcc0/planta_de_ramie_foto_en-wikipedia-org_wiki_ramie.jpg',
                'tags'           => 'alimentacion,animales,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Bambú',
                'cientifico'     => 'Bambusa vulgaris',
                'categoria'      => 'Cultura',
                'subtema'        => 'Construcción ancestral',
                'uso'            => 'Material de construcción',
                'instrucciones'  => 'Se usan los tallos como material estructural.',
                'contexto'       => 'Origen: cultivada.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fd/Bamboo_2%2C_Jacksonville_Zoo.jpg/960px-Bamboo_2%2C_Jacksonville_Zoo.jpg',
                'tags'           => 'cultura,construccion,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Guadua',
                'cientifico'     => 'Guadua angustifolia',
                'categoria'      => 'Cultura',
                'subtema'        => 'Construcción ancestral',
                'uso'            => 'Material de construcción',
                'instrucciones'  => 'Se usan los tallos como material estructural.',
                'contexto'       => 'Origen: cultivada.',
                'img_url'        => 'https://upload.wikimedia.org/wikipedia/commons/0/02/Guadua.jpg',
                'tags'           => 'cultura,construccion,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Palma de Vino',
                'cientifico'     => 'Attalea butyracea',
                'categoria'      => 'Cultura',
                'subtema'        => 'Construcción ancestral',
                'uso'            => 'Material de construcción',
                'instrucciones'  => 'Se usa el tallo, las hojas y las semillas para construcción.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRs9qzjNEKxeCBZhlnEsiOO7owGSxvRInY8j41P2mU_jTxhgEJfLg8Qkxgr&s=10',
                'tags'           => 'cultura,construccion,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Bambú',
                'cientifico'     => 'Bambusa vulgaris',
                'categoria'      => 'Cultura',
                'subtema'        => 'Tejidos y artesanías',
                'uso'            => 'Elaboración de artesanías',
                'instrucciones'  => 'Se trabajan los tallos para tejer artesanías.',
                'contexto'       => 'Origen: cultivada.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fd/Bamboo_2%2C_Jacksonville_Zoo.jpg/960px-Bamboo_2%2C_Jacksonville_Zoo.jpg',
                'tags'           => 'cultura,artesania,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Palma de Vino',
                'cientifico'     => 'Attalea butyracea',
                'categoria'      => 'Cultura',
                'subtema'        => 'Tejidos y artesanías',
                'uso'            => 'Elaboración de artesanías',
                'instrucciones'  => 'Se usa el tallo, las hojas y las semillas para artesanías.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRs9qzjNEKxeCBZhlnEsiOO7owGSxvRInY8j41P2mU_jTxhgEJfLg8Qkxgr&s=10',
                'tags'           => 'cultura,artesania,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Totumo',
                'cientifico'     => 'Crescentia cujete',
                'categoria'      => 'Cultura',
                'subtema'        => 'Tejidos y artesanías',
                'uso'            => 'Elaboración de artesanías con el fruto',
                'instrucciones'  => 'Se usa el fruto seco y ahuecado para elaborar utensilios y artesanías.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://upload.wikimedia.org/wikipedia/commons/2/22/Daotien.jpg',
                'tags'           => 'cultura,artesania,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Tabaco',
                'cientifico'     => 'Nicotiana tabacum',
                'categoria'      => 'Cultura',
                'subtema'        => 'Rituales y ceremonias',
                'uso'            => 'Planta sagrada de uso ritual',
                'instrucciones'  => 'Se usa la planta completa en ceremonias tradicionales.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8e/Patch_of_Tobacco_%28Nicotiana_tabacum_%29_in_a_field_in_Intercourse%2C_Pennsylvania..jpg/250px-Patch_of_Tobacco_%28Nicotiana_tabacum_%29_in_a_field_in_Intercourse%2C_Pennsylvania..jpg',
                'tags'           => 'cultura,rituales,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Sábila',
                'cientifico'     => 'Aloe vera',
                'categoria'      => 'Cultura',
                'subtema'        => 'Rituales y ceremonias',
                'uso'            => 'Uso ritual y energético',
                'instrucciones'  => 'Se coloca la hoja o el tallo en el espacio ritual.',
                'contexto'       => 'Origen: cultivada y silvestre.',
                'img_url'        => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqRklqzB7gPkWLX1cVWdTwohhyxyt7Bqfo-ftVoigPzA&s',
                'tags'           => 'cultura,rituales,sumapaz',
                'verificada'     => true,
            ],
            [
                'nombre'         => 'Aliso',
                'cientifico'     => 'Alnus acuminata',
                'categoria'      => 'Cultura',
                'subtema'        => 'Cuidado ambiental',
                'uso'            => 'Conservación de fuentes de agua',
                'instrucciones'  => 'Se usa como planta indicadora y protectora de cuerpos de agua; no requiere preparación.',
                'contexto'       => 'Reportada como planta bioindicadora para la conservación ambiental. Origen: silvestre.',
                'img_url'        => 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Alnus_glutinosa_011.jpg',
                'tags'           => 'cultura,ambiental,sumapaz',
                'verificada'     => true,
            ],
        ];

        foreach ($plantas as $planta) {
            $categoriaId = $categoriaIds[$planta['categoria']];
            $subtemaIdVal = $subtemaId($planta['categoria'], $planta['subtema']);

            if (!$subtemaIdVal) {
                continue; // subtema no encontrado; no debería pasar
            }

            DB::table('plantas')->updateOrInsert(
                [
                    'nombre'       => $planta['nombre'],
                    'categoria_id' => $categoriaId,
                    'subtema_id'   => $subtemaIdVal,
                ],
                [
                    'cientifico'     => $planta['cientifico'],
                    'categoria_id'   => $categoriaId,
                    'subtema_id'     => $subtemaIdVal,
                    'uso'            => $planta['uso'],
                    'instrucciones'  => $planta['instrucciones'],
                    'contexto'       => $planta['contexto'],
                    'relato'         => null,
                    'video_url'      => null,
                    'img_url'        => $planta['img_url'],
                    'img_path'       => null,
                    'verificada'     => $planta['verificada'],
                    'tags'           => $planta['tags'],
                    'creado_en'      => now(),
                    'actualizado_en' => now(),
                ]
            );
        }
    }
}
